FROM python:3.11-slim

WORKDIR /app

RUN pip install --no-cache-dir uv

COPY pyproject.toml uv.lock ./
COPY src/ src/
RUN uv sync --extra api --extra rag --no-dev

# Copy pre-built data artefacts
# (these are generated by the pipeline before building the image)
COPY data/processed/ data/processed/
COPY data/index/ data/index/
COPY results/ results/

ENV DATA_DIR=/app/data
ENV PORT=8000

EXPOSE 8000

CMD sh -c "uvicorn cobol_archaeologist.api.main:app --host 0.0.0.0 --port ${PORT}"
