FROM python:3.11-slim

WORKDIR /app

# Install dependencies
COPY pyproject.toml .
COPY src/ src/
RUN pip install --no-cache-dir -e ".[api,rag]"

# Copy pre-built data artefacts
# (these are generated by the pipeline before building the image)
COPY data/processed/ data/processed/
COPY data/index/ data/index/
COPY reports/ reports/

ENV DATA_DIR=/app/data
ENV PORT=8000

EXPOSE 8000

CMD ["uvicorn", "cobol_archaeologist.api.main:app", "--host", "0.0.0.0", "--port", "8000"]
